<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ app()->getLocale()==='ar'?'إدارة العمليات':'Operations Management' }} · FOODEX</title>
@include('admin._brand-components')
<style>
body{margin:0;background:var(--foodex-background);color:var(--foodex-ink)}
.layout{direction:ltr;display:grid;grid-template-columns:minmax(0,1fr) var(--foodex-sidebar-width);min-height:100vh}
.layout aside{grid-column:2;grid-row:1;direction:rtl;background:var(--foodex-surface);border-left:1px solid var(--foodex-border);padding:var(--foodex-space-5)}
.layout main{grid-column:1;grid-row:1;direction:rtl;padding:var(--foodex-space-6);min-width:0}
html[dir=ltr] .layout{grid-template-columns:var(--foodex-sidebar-width) minmax(0,1fr)}html[dir=ltr] .layout aside{grid-column:1;direction:ltr;border-left:0;border-right:1px solid var(--foodex-border)}html[dir=ltr] .layout main{grid-column:2;direction:ltr}
.header{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:14px}.header h1{margin:0}.muted{color:var(--foodex-muted)}
.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.tabs a,.btn{border:1px solid var(--foodex-border);background:#fff;color:var(--foodex-ink);border-radius:10px;padding:9px 12px;text-decoration:none;font:inherit;cursor:pointer}.tabs a.active,.btn.primary{background:var(--foodex-green);color:#fff;border-color:var(--foodex-green)}.btn.danger{color:var(--foodex-red)}
.grid{display:grid;grid-template-columns:minmax(280px,360px) minmax(0,1fr);gap:14px}.card{background:#fff;border:1px solid var(--foodex-border);border-radius:var(--foodex-radius-card);padding:15px}.form{display:grid;gap:9px}.form input,.form select,.form textarea{width:100%;box-sizing:border-box;border:1px solid var(--foodex-border);border-radius:9px;padding:9px;font:inherit}.form label{font-weight:700;font-size:.84rem}.check{display:flex;gap:7px;align-items:center}.check input{width:auto}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:760px}.table th,.table td{padding:9px;border-bottom:1px solid var(--foodex-border);text-align:start;vertical-align:top}.table th{background:var(--foodex-background)}
.inline{display:flex;gap:6px;flex-wrap:wrap}.inline input,.inline select{max-width:165px;padding:7px;border:1px solid var(--foodex-border);border-radius:8px}.notice{padding:10px;border-radius:9px;margin-bottom:12px}.ok{background:var(--foodex-green-soft)}.err{background:#fff1f0;color:var(--foodex-red)}
@media(max-width:1000px){.grid{grid-template-columns:1fr}.layout{grid-template-columns:1fr}.layout aside,.layout main,html[dir=ltr] .layout aside,html[dir=ltr] .layout main{grid-column:1}.layout aside{grid-row:1}.layout main{grid-row:2}}
</style>
</head>
<body><div class="layout"><aside class="sidebar">@include('admin._sidebar')</aside><main>
<div class="header"><div><h1>{{ app()->getLocale()==='ar'?'إدارة العمليات والبيانات':'Operations & Data Management' }}</h1><div class="muted">{{ app()->getLocale()==='ar'?'إضافة وتعديل وحذف البيانات التشغيلية من مكان واحد.':'Create, edit and remove operational data from one place.' }}</div></div><a class="btn" href="{{ route('admin.index') }}">{{ app()->getLocale()==='ar'?'لوحة الإدارة':'Dashboard' }}</a></div>
@if(session('status'))<div class="notice ok">{{ session('status') }}</div>@endif
@if($errors->any())<div class="notice err">@foreach($errors->all() as $e)<div>{{ $e }}</div>@endforeach</div>@endif
<nav class="tabs">@foreach(['inventory'=>'المخزون','customers'=>'العملاء','promotions'=>'العروض','content'=>'المحتوى والبنرات','drivers'=>'السائقون'] as $key=>$ar)<a class="{{ $tab===$key?'active':'' }}" href="{{ route('admin.business.index',['tab'=>$key]) }}">{{ app()->getLocale()==='ar'?$ar:ucfirst($key) }}</a>@endforeach</nav>

@if($tab==='inventory')
<div class="grid"><section class="card"><h2>{{ app()->getLocale()==='ar'?'إضافة مخزن / رصيد':'Warehouse / Inventory' }}</h2>
<form class="form" method="post" action="{{ route('admin.business.warehouses.store') }}">@csrf<label>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'كود المخزن':'Warehouse code' }}<input name="code" required></label><label>{{ app()->getLocale()==='ar'?'اسم المخزن':'Warehouse name' }}<input name="name" required></label><label class="check"><input type="checkbox" name="is_active" value="1" checked>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn primary">{{ app()->getLocale()==='ar'?'إضافة مخزن':'Add warehouse' }}</button></form>
<hr><form class="form" method="post" action="{{ route('admin.business.inventory.ensure') }}">@csrf<label>{{ app()->getLocale()==='ar'?'المخزن':'Warehouse' }}<select name="warehouse_id">@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'المنتج':'Product' }}<select name="product_id">@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} — {{ $p->sku }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'الكمية':'Quantity' }}<input type="number" step=".001" min="0" name="quantity" value="0"></label><button class="btn primary">{{ app()->getLocale()==='ar'?'إنشاء/تحديث الرصيد':'Create/update balance' }}</button></form></section>
<section class="card table-wrap"><table class="table"><thead><tr><th>SKU</th><th>{{ app()->getLocale()==='ar'?'المنتج':'Product' }}</th><th>{{ app()->getLocale()==='ar'?'المخزن':'Warehouse' }}</th><th>{{ app()->getLocale()==='ar'?'الكمية':'Qty' }}</th><th>{{ app()->getLocale()==='ar'?'تعديل الرصيد':'Adjust' }}</th></tr></thead><tbody>@foreach($inventories as $i)<tr><td>{{ $i->sku }}</td><td>{{ $i->product }}</td><td>{{ $i->warehouse }}</td><td>{{ $i->quantity }} / {{ $i->reserved_quantity }}</td><td><form class="inline" method="post" action="{{ route('admin.business.inventory.adjust',$i->id) }}">@csrf @method('PATCH')<input type="number" step=".001" name="quantity_delta" placeholder="+/-"><input name="reason" placeholder="{{ app()->getLocale()==='ar'?'السبب':'Reason' }}"><button class="btn">{{ app()->getLocale()==='ar'?'تنفيذ':'Apply' }}</button></form></td></tr>@endforeach</tbody></table></section></div>

@elseif($tab==='customers')
<div class="grid"><section class="card"><h2>{{ app()->getLocale()==='ar'?'إضافة عميل':'Add customer' }}</h2>
@if($user->hasRole('SUPER_ADMIN') && !$supportStoreId)
<div class="notice">{{ app()->getLocale()==='ar'?'عملاء التجزئة لا يظهرون للسوبر أدمن إلا بعد الدخول الصريح لمتجر للدعم.':'Retail customers stay hidden from SUPER_ADMIN until explicit store support access is entered.' }}</div>
@endif
<form class="form" method="post" action="{{ route('admin.business.customers.store') }}">@csrf
@if($supportStoreId)<input type="hidden" name="support_access" value="1">@endif
<label>{{ app()->getLocale()==='ar'?'النطاق':'Domain' }}<select name="type"><option value="b2c">B2C</option>@if($user->hasRole('SUPER_ADMIN') || $user->hasRole('B2B_ADMIN'))<option value="b2b">B2B</option>@endif</select></label>
<label>{{ app()->getLocale()==='ar'?'متجر B2C':'B2C store' }}<select name="store_id"><option value="">—</option>@foreach($customerStores as $s)<option value="{{ $s->id }}">{{ $s->name }} — {{ $s->code }}</option>@endforeach</select></label>
<label>{{ app()->getLocale()==='ar'?'الاسم':'Name' }}<input name="name" required></label><label>{{ app()->getLocale()==='ar'?'الهاتف':'Phone' }}<input name="phone"></label><label>{{ app()->getLocale()==='ar'?'البريد':'Email' }}<input type="email" name="email"></label><button class="btn primary">{{ app()->getLocale()==='ar'?'إضافة العميل':'Add customer' }}</button></form></section>
<section class="card table-wrap"><table class="table"><thead><tr><th>{{ app()->getLocale()==='ar'?'الاسم':'Name' }}</th><th>{{ app()->getLocale()==='ar'?'النطاق':'Domain' }}</th><th>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}</th><th>{{ app()->getLocale()==='ar'?'الاتصال':'Contact' }}</th><th>{{ app()->getLocale()==='ar'?'إجراءات':'Actions' }}</th></tr></thead><tbody>
@foreach($customers as $c)<tr><td>{{ $c->name }}</td><td>{{ strtoupper($c->type) }}</td><td>{{ $c->store ?: '—' }}</td><td>{{ $c->phone }}<br>{{ $c->email }}</td><td>
<form class="inline" method="post" action="{{ route('admin.business.customers.update',$c->id) }}">@csrf @method('PATCH')<input type="hidden" name="type" value="{{ $c->type }}">@if($supportStoreId && $c->type==='b2c')<input type="hidden" name="support_access" value="1">@endif<input name="name" value="{{ $c->name }}"><input name="phone" value="{{ $c->phone }}"><input type="email" name="email" value="{{ $c->email }}"><button class="btn">{{ app()->getLocale()==='ar'?'حفظ':'Save' }}</button></form>
<form method="post" action="{{ route('admin.business.customers.destroy',$c->id) }}" style="margin-top:6px">@csrf @method('DELETE')<input type="hidden" name="type" value="{{ $c->type }}">@if($supportStoreId && $c->type==='b2c')<input type="hidden" name="support_access" value="1">@endif<button class="btn danger">{{ app()->getLocale()==='ar'?'حذف':'Delete' }}</button></form>
</td></tr>@endforeach</tbody></table></section></div>

@elseif($tab==='promotions')
<div class="grid"><section class="card"><h2>{{ app()->getLocale()==='ar'?'إضافة عرض':'Add promotion' }}</h2><form class="form" method="post" action="{{ route('admin.business.promotions.store') }}">@csrf<label>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'الاسم':'Name' }}<input name="name" required></label><label>{{ app()->getLocale()==='ar'?'النوع':'Type' }}<input name="type" value="percentage" required></label><label>{{ app()->getLocale()==='ar'?'القيمة':'Value' }}<input type="number" step=".001" min="0" name="value"></label><div class="row"><label>{{ app()->getLocale()==='ar'?'من':'From' }}<input type="datetime-local" name="starts_at"></label><label>{{ app()->getLocale()==='ar'?'إلى':'To' }}<input type="datetime-local" name="ends_at"></label></div><label class="check"><input type="checkbox" name="is_active" value="1" checked>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn primary">{{ app()->getLocale()==='ar'?'إضافة العرض':'Add promotion' }}</button></form></section>
<section class="card table-wrap"><table class="table"><thead><tr><th>{{ app()->getLocale()==='ar'?'العرض':'Promotion' }}</th><th>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}</th><th>{{ app()->getLocale()==='ar'?'القيمة':'Value' }}</th><th>{{ app()->getLocale()==='ar'?'إجراءات':'Actions' }}</th></tr></thead><tbody>@foreach($promotions as $p)<tr><td>{{ $p->name }}<br><small>{{ $p->type }}</small></td><td>{{ $p->store ?: '—' }}</td><td>{{ $p->value }}</td><td><form class="inline" method="post" action="{{ route('admin.business.promotions.update',$p->id) }}">@csrf @method('PATCH')<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}" @selected($p->store_id==$s->id)>{{ $s->name }}</option>@endforeach</select><input name="name" value="{{ $p->name }}"><input name="type" value="{{ $p->type }}"><input type="number" step=".001" min="0" name="value" value="{{ $p->value }}"><input type="hidden" name="starts_at" value="{{ $p->starts_at }}"><input type="hidden" name="ends_at" value="{{ $p->ends_at }}"><label class="check"><input type="checkbox" name="is_active" value="1" @checked($p->is_active)>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn">{{ app()->getLocale()==='ar'?'حفظ':'Save' }}</button></form><form method="post" action="{{ route('admin.business.promotions.destroy',$p->id) }}" style="margin-top:6px">@csrf @method('DELETE')<button class="btn danger">{{ app()->getLocale()==='ar'?'حذف':'Delete' }}</button></form></td></tr>@endforeach</tbody></table></section></div>

@elseif($tab==='content')
<div class="grid"><section class="card"><h2>{{ app()->getLocale()==='ar'?'إضافة بانر':'Add banner' }}</h2><form class="form" method="post" action="{{ route('admin.business.banners.store') }}">@csrf<label>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'العنوان':'Title' }}<input name="title" required></label><label>{{ app()->getLocale()==='ar'?'مسار الصورة':'Image path' }}<input name="image_path" required></label><label>{{ app()->getLocale()==='ar'?'الرابط':'Target URL' }}<input name="target_url"></label><label>{{ app()->getLocale()==='ar'?'الترتيب':'Sort order' }}<input type="number" min="0" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn primary">{{ app()->getLocale()==='ar'?'إضافة البانر':'Add banner' }}</button></form></section>
<section class="card table-wrap"><table class="table"><thead><tr><th>{{ app()->getLocale()==='ar'?'العنوان':'Title' }}</th><th>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}</th><th>{{ app()->getLocale()==='ar'?'إجراءات':'Actions' }}</th></tr></thead><tbody>@foreach($banners as $b)<tr><td>{{ $b->title }}<br><small>{{ $b->image_path }}</small></td><td>{{ $b->store ?: '—' }}</td><td><form class="inline" method="post" action="{{ route('admin.business.banners.update',$b->id) }}">@csrf @method('PATCH')<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}" @selected($b->store_id==$s->id)>{{ $s->name }}</option>@endforeach</select><input name="title" value="{{ $b->title }}"><input name="image_path" value="{{ $b->image_path }}"><input name="target_url" value="{{ $b->target_url }}"><input type="number" min="0" name="sort_order" value="{{ $b->sort_order }}"><label class="check"><input type="checkbox" name="is_active" value="1" @checked($b->is_active)>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn">{{ app()->getLocale()==='ar'?'حفظ':'Save' }}</button></form><form method="post" action="{{ route('admin.business.banners.destroy',$b->id) }}" style="margin-top:6px">@csrf @method('DELETE')<button class="btn danger">{{ app()->getLocale()==='ar'?'حذف':'Delete' }}</button></form></td></tr>@endforeach</tbody></table></section></div>

@elseif($tab==='drivers')
<div class="grid"><section class="card"><h2>{{ app()->getLocale()==='ar'?'إضافة سائق':'Add driver' }}</h2><form class="form" method="post" action="{{ route('admin.business.drivers.store') }}">@csrf<label>{{ app()->getLocale()==='ar'?'الاسم':'Name' }}<input name="name" required></label><label>{{ app()->getLocale()==='ar'?'البريد':'Email' }}<input type="email" name="email" required></label><label>{{ app()->getLocale()==='ar'?'كلمة المرور':'Password' }}<input type="password" name="password" required></label><label>{{ app()->getLocale()==='ar'?'المتجر':'Store' }}<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>{{ app()->getLocale()==='ar'?'النوع':'Type' }}<select name="driver_type"><option value="b2c">B2C</option><option value="b2b">B2B</option></select></label><label class="check"><input type="checkbox" name="is_available" value="1">{{ app()->getLocale()==='ar'?'متاح':'Available' }}</label><label class="check"><input type="checkbox" name="is_active" value="1" checked>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn primary">{{ app()->getLocale()==='ar'?'إضافة السائق':'Add driver' }}</button></form></section>
<section class="card table-wrap"><table class="table"><thead><tr><th>{{ app()->getLocale()==='ar'?'السائق':'Driver' }}</th><th>{{ app()->getLocale()==='ar'?'النوع':'Type' }}</th><th>{{ app()->getLocale()==='ar'?'الحالة':'Status' }}</th><th>{{ app()->getLocale()==='ar'?'إجراءات':'Actions' }}</th></tr></thead><tbody>@foreach($drivers as $d)<tr><td>{{ $d->name }}<br><small>{{ $d->email }}</small></td><td>{{ $d->driver_type }}</td><td>{{ $d->is_active?'Active':'Inactive' }} / {{ $d->is_available?'Available':'Busy' }}</td><td><form class="inline" method="post" action="{{ route('admin.business.drivers.update',$d->id) }}">@csrf @method('PATCH')<select name="store_id" required>@foreach($stores as $s)<option value="{{ $s->id }}" @selected($d->store_id==$s->id)>{{ $s->name }}</option>@endforeach</select><select name="driver_type"><option value="b2c" @selected($d->driver_type==='b2c')>B2C</option><option value="b2b" @selected($d->driver_type==='b2b')>B2B</option></select><label class="check"><input type="checkbox" name="is_available" value="1" @checked($d->is_available)>{{ app()->getLocale()==='ar'?'متاح':'Available' }}</label><label class="check"><input type="checkbox" name="is_active" value="1" @checked($d->is_active)>{{ app()->getLocale()==='ar'?'نشط':'Active' }}</label><button class="btn">{{ app()->getLocale()==='ar'?'حفظ':'Save' }}</button></form><form method="post" action="{{ route('admin.business.drivers.destroy',$d->id) }}" style="margin-top:6px">@csrf @method('DELETE')<button class="btn danger">{{ app()->getLocale()==='ar'?'حذف':'Delete' }}</button></form></td></tr>@endforeach</tbody></table></section></div>
@endif
</main></div></body></html>