<!doctype html><html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ __('mobile_settings.title') }}</title>
<style>body{margin:0;background:#f6f7f9;color:#17202a}.layout{display:grid;grid-template-columns:var(--foodex-sidebar-width) minmax(0,1fr);min-height:100vh;width:100%}.sidebar{background:#111827;color:#fff;padding:20px}.main{min-width:0;width:100%;padding:clamp(16px,1.8vw,32px)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:20px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}label{display:block;font-weight:650;font-size:.85rem;margin:9px 0 5px}input,select,textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #cbd5e1;border-radius:10px}textarea{min-height:70px}.check{display:flex;align-items:center;gap:8px}.check input{width:auto}.button{margin-top:12px;padding:10px 14px;border:0;border-radius:10px;background:#0f172a;color:#fff}.notice{padding:12px;background:#ecfdf5;border-radius:10px;margin-bottom:14px}.muted{color:#64748b}.log{padding:8px 0;border-top:1px solid #e2e8f0}@media(max-width:1023px){.layout{grid-template-columns:1fr}.row{grid-template-columns:1fr}}</style>    @include('admin._brand-components')
</head><body>@php($ar = app()->getLocale()==='ar')<div class="layout foodex-admin-layout" data-foodex-utility="mobile-settings">
<aside class="sidebar">@include('admin._sidebar',['navGroups'=>app(\App\Support\AdminNavigation::class)->groupsFor(auth()->user()),'navContext'=>'mobile_settings','user'=>auth()->user()])</aside><main class="main foodex-admin-main">
<header class="foodex-page-header"><div><h1>{{ __('mobile_settings.title') }}</h1><p class="muted">{{ __('mobile_settings.description') }}</p></div>@include('admin._live-notifications',['user'=>auth()->user()])</header>@if(session('status'))<div class="notice foodex-state" role="status">{{ session('status') }}</div>@endif @if($errors->any())<div class="error foodex-state" role="alert">{{ $errors->first() }}</div>@endif
<div class="grid"><section class="card"><h2>{{ __('mobile_settings.runtime_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.app') }}">@csrf @method('put')
<div class="row"><div><label>{{ __('mobile_settings.app') }}</label><select name="app"><option value="customer">{{ $ar?'العميل':'Customer' }}</option><option value="driver">{{ $ar?'السائق':'Driver' }}</option></select></div><div><label>{{ __('mobile_settings.environment') }}</label><select name="environment"><option value="development">{{ $ar?'تطوير':'Development' }}</option><option value="staging">{{ $ar?'اختبار':'Staging' }}</option><option value="production" selected>{{ $ar?'إنتاج':'Production' }}</option></select></div></div>
<label>{{ __('mobile_settings.display_name') }}</label><input name="display_name" placeholder="{{ $ar?'مثال: فودكس العميل':'e.g. FOODEX Customer' }}" required><div class="row"><div><label>{{ $ar?'معرّف حزمة أندرويد':'Android package ID' }}</label><input name="android_package_id" placeholder="com.fiftysolution.foodex.customer"></div><div><label>{{ $ar?'معرّف حزمة آي أو إس':'iOS bundle ID' }}</label><input name="ios_bundle_id" placeholder="com.fiftysolution.foodex.customer"></div></div>
<div class="row"><div><label>{{ __('mobile_settings.published_version') }}</label><input name="published_version" placeholder="1.0.12"></div><div><label>{{ __('mobile_settings.published_build') }}</label><input name="published_build" placeholder="112"></div></div>
<div class="row"><div><label>{{ __('mobile_settings.minimum_version') }}</label><input name="minimum_supported_version" placeholder="1.0.6"></div><div><label>{{ __('mobile_settings.recommended_version') }}</label><input name="recommended_version" placeholder="1.0.12"></div></div>
<label class="check"><input type="checkbox" name="force_update" value="1">{{ __('mobile_settings.force_update') }}</label><label class="check"><input type="checkbox" name="maintenance_mode" value="1">{{ __('mobile_settings.maintenance') }}</label>
<div class="row"><div><label>{{ __('mobile_settings.message_ar') }}</label><textarea name="maintenance_message_ar" placeholder="رسالة الصيانة بالعربية"></textarea></div><div><label>{{ __('mobile_settings.message_en') }}</label><textarea name="maintenance_message_en" placeholder="Maintenance message in English"></textarea></div></div>
<label>{{ $ar?'رابط متجر جوجل بلاي':'Google Play URL' }}</label><input type="url" name="google_play_url" placeholder="https://play.google.com/store/apps/details?id=..."><label>{{ $ar?'رابط متجر آب ستور':'App Store URL' }}</label><input type="url" name="app_store_url" placeholder="https://apps.apple.com/app/id..."><div class="row"><div><label>{{ $ar?'رابط سياسة الخصوصية':'Privacy URL' }}</label><input type="url" name="privacy_url" placeholder="https://example.com/privacy"></div><div><label>{{ $ar?'رابط الشروط والأحكام':'Terms URL' }}</label><input type="url" name="terms_url" placeholder="https://example.com/terms"></div></div><label>{{ $ar?'رابط الدعم':'Support URL' }}</label><input type="url" name="support_url" placeholder="https://example.com/support">
<div class="row"><div><label>{{ __('mobile_settings.release_ar') }}</label><textarea name="release_notes_ar" placeholder="ملاحظات الإصدار بالعربية"></textarea></div><div><label>{{ __('mobile_settings.release_en') }}</label><textarea name="release_notes_en" placeholder="Release notes in English"></textarea></div></div>
<label>{{ __('mobile_settings.deep_links') }}</label><textarea name="deep_link_json" placeholder="{&quot;scheme&quot;:&quot;foodex&quot;,&quot;host&quot;:&quot;app&quot;}"></textarea><label>{{ __('mobile_settings.readiness') }}</label><textarea name="store_readiness_json" placeholder="{&quot;android&quot;:true,&quot;ios&quot;:true}"></textarea><button class="button">{{ __('mobile_settings.save') }}</button></form></section>
<section class="card"><h2>{{ __('mobile_settings.push_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.push') }}">@csrf @method('put')
<div class="row"><div><label>{{ __('mobile_settings.app') }}</label><select name="app"><option value="customer">{{ $ar?'العميل':'Customer' }}</option><option value="driver">{{ $ar?'السائق':'Driver' }}</option></select></div><div><label>{{ __('mobile_settings.platform') }}</label><select name="platform"><option value="android">{{ $ar?'أندرويد / إشعارات فايربيز':'Android / FCM' }}</option><option value="ios">{{ $ar?'آي أو إس / إشعارات فايربيز':'iOS / FCM (APNs)' }}</option></select></div></div>
<label>{{ __('mobile_settings.environment') }}</label><select name="environment"><option value="development">{{ $ar?'تطوير':'Development' }}</option><option value="staging">{{ $ar?'اختبار':'Staging' }}</option><option value="production" selected>{{ $ar?'إنتاج':'Production' }}</option></select><label class="check"><input type="checkbox" name="enabled" value="1">{{ __('mobile_settings.enabled') }}</label>
<label>{{ __('mobile_settings.credentials') }}</label><textarea name="credentials_json" placeholder="{{ $ar?'ألصق Service Account JSON من Firebase / Google Cloud ويشمل project_id و client_email و private_key':'Paste the Firebase / Google Cloud Service Account JSON including project_id, client_email and private_key' }}"></textarea><p class="muted">{{ $ar?'يحفظ مشفراً. يقوم FOODEX بإنشاء وتجديد OAuth access token تلقائياً؛ لا تحتاج لإدخال access_token يدوياً.':'Stored encrypted. FOODEX generates and refreshes the OAuth access token automatically; no manual access_token is required.' }}</p><div class="row"><div><label>{{ $ar?'الصوت الافتراضي':'Sound' }}</label><input name="default_sound" placeholder="default"></div><div><label>{{ $ar?'قناة الإشعارات':'Channel' }}</label><input name="default_channel" placeholder="foodex_default"></div></div><div class="row"><div><label>{{ $ar?'أيقونة الإشعار':'Icon' }}</label><input name="default_icon" placeholder="ic_notification"></div><div><label>{{ $ar?'فئة الإشعار':'Category' }}</label><input name="default_category" placeholder="general"></div></div><button class="button">{{ __('mobile_settings.save_push') }}</button></form>
<h3>{{ __('mobile_settings.configured') }}</h3>@forelse($providers as $p)<div class="log" style="display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap"><span>{{ $p->app }} · {{ $p->platform }} · {{ $p->environment }} · {{ $p->enabled?__('mobile_settings.on'):__('mobile_settings.off') }}</span><form method="post" action="{{ route('admin.mobile-settings.push.test') }}" style="margin:0">@csrf<input type="hidden" name="app" value="{{ $p->app }}"><input type="hidden" name="platform" value="{{ $p->platform }}"><input type="hidden" name="environment" value="{{ $p->environment }}"><button class="button" type="submit" style="margin:0">{{ $ar?'اختبار اتصال Firebase':'Test Firebase connection' }}</button></form></div>@empty<p class="muted">{{ __('mobile_settings.empty') }}</p>@endforelse</section>
<section class="card"><h2>{{ __('mobile_settings.test_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.test') }}">@csrf<label>{{ __('mobile_settings.device') }}</label><select name="device_id">@foreach($devices as $d)<option value="{{ $d->id }}">#{{ $d->id }} · {{ $d->app }} · {{ $d->platform }} · {{ $d->environment }}</option>@endforeach</select>
<div class="row"><div><label>{{ __('mobile_settings.title_ar') }}</label><input name="title_ar" placeholder="عنوان الإشعار بالعربية" required></div><div><label>{{ __('mobile_settings.title_en') }}</label><input name="title_en" placeholder="Notification title in English" required></div></div><div class="row"><div><label>{{ __('mobile_settings.body_ar') }}</label><textarea name="body_ar" placeholder="نص الإشعار بالعربية" required></textarea></div><div><label>{{ __('mobile_settings.body_en') }}</label><textarea name="body_en" placeholder="Notification body in English" required></textarea></div></div><button class="button">{{ __('mobile_settings.send_test') }}</button></form>
<h3>{{ __('mobile_settings.delivery_log') }}</h3>@forelse($logs as $log)<div class="log">#{{ $log->id }} · {{ $log->app }}/{{ $log->platform }}/{{ $log->environment }} · <strong>{{ $log->status }}</strong>@if($log->response_code) · HTTP {{ $log->response_code }}@endif @if($log->error_code)<br><strong>{{ $ar?'السبب':'Reason' }}:</strong> {{ $log->error_code }}@if($log->error_message) — {{ $log->error_message }}@endif @endif</div>@empty<p class="muted">{{ __('mobile_settings.empty') }}</p>@endforelse</section></div></main></div></body></html>
