<!doctype html><html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ __('mobile_settings.title') }}</title>
<style>body{margin:0;font-family:system-ui;background:#f6f7f9;color:#17202a}.layout{display:grid;grid-template-columns:270px 1fr;min-height:100vh}.sidebar{background:#111827;color:#fff;padding:20px}.main{padding:28px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:20px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}label{display:block;font-weight:650;font-size:.85rem;margin:9px 0 5px}input,select,textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #cbd5e1;border-radius:10px}textarea{min-height:70px}.check{display:flex;align-items:center;gap:8px}.check input{width:auto}.button{margin-top:12px;padding:10px 14px;border:0;border-radius:10px;background:#0f172a;color:#fff}.notice{padding:12px;background:#ecfdf5;border-radius:10px;margin-bottom:14px}.muted{color:#64748b}.log{padding:8px 0;border-top:1px solid #e2e8f0}@media(max-width:760px){.layout{grid-template-columns:1fr}.row{grid-template-columns:1fr}}</style></head><body><div class="layout">
<aside class="sidebar">@include('admin._sidebar',['navGroups'=>app(\App\Support\AdminNavigation::class)->groupsFor(auth()->user()),'navContext'=>'mobile_settings','user'=>auth()->user()])</aside><main class="main">
<h1>{{ __('mobile_settings.title') }}</h1><p class="muted">{{ __('mobile_settings.description') }}</p>@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="notice">{{ $errors->first() }}</div>@endif
<div class="grid"><section class="card"><h2>{{ __('mobile_settings.runtime_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.app') }}">@csrf @method('put')
<div class="row"><div><label>{{ __('mobile_settings.app') }}</label><select name="app"><option value="customer">Customer</option><option value="driver">Driver</option></select></div><div><label>{{ __('mobile_settings.environment') }}</label><select name="environment"><option>development</option><option>staging</option><option selected>production</option></select></div></div>
<label>{{ __('mobile_settings.display_name') }}</label><input name="display_name" required><div class="row"><div><label>Android package ID</label><input name="android_package_id"></div><div><label>iOS bundle ID</label><input name="ios_bundle_id"></div></div>
<div class="row"><div><label>{{ __('mobile_settings.published_version') }}</label><input name="published_version"></div><div><label>{{ __('mobile_settings.published_build') }}</label><input name="published_build"></div></div>
<div class="row"><div><label>{{ __('mobile_settings.minimum_version') }}</label><input name="minimum_supported_version"></div><div><label>{{ __('mobile_settings.recommended_version') }}</label><input name="recommended_version"></div></div>
<label class="check"><input type="checkbox" name="force_update" value="1">{{ __('mobile_settings.force_update') }}</label><label class="check"><input type="checkbox" name="maintenance_mode" value="1">{{ __('mobile_settings.maintenance') }}</label>
<div class="row"><div><label>{{ __('mobile_settings.message_ar') }}</label><textarea name="maintenance_message_ar"></textarea></div><div><label>{{ __('mobile_settings.message_en') }}</label><textarea name="maintenance_message_en"></textarea></div></div>
<label>Google Play URL</label><input type="url" name="google_play_url"><label>App Store URL</label><input type="url" name="app_store_url"><div class="row"><div><label>Privacy URL</label><input type="url" name="privacy_url"></div><div><label>Terms URL</label><input type="url" name="terms_url"></div></div><label>Support URL</label><input type="url" name="support_url">
<div class="row"><div><label>{{ __('mobile_settings.release_ar') }}</label><textarea name="release_notes_ar"></textarea></div><div><label>{{ __('mobile_settings.release_en') }}</label><textarea name="release_notes_en"></textarea></div></div>
<label>{{ __('mobile_settings.deep_links') }}</label><textarea name="deep_link_json"></textarea><label>{{ __('mobile_settings.readiness') }}</label><textarea name="store_readiness_json"></textarea><button class="button">{{ __('mobile_settings.save') }}</button></form></section>
<section class="card"><h2>{{ __('mobile_settings.push_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.push') }}">@csrf @method('put')
<div class="row"><div><label>{{ __('mobile_settings.app') }}</label><select name="app"><option value="customer">Customer</option><option value="driver">Driver</option></select></div><div><label>{{ __('mobile_settings.platform') }}</label><select name="platform"><option value="android">Android / FCM</option><option value="ios">iOS / APNs</option></select></div></div>
<label>{{ __('mobile_settings.environment') }}</label><select name="environment"><option>development</option><option>staging</option><option selected>production</option></select><label class="check"><input type="checkbox" name="enabled" value="1">{{ __('mobile_settings.enabled') }}</label>
<label>{{ __('mobile_settings.credentials') }}</label><textarea name="credentials_json"></textarea><p class="muted">{{ __('mobile_settings.secret_hint') }}</p><div class="row"><div><label>Sound</label><input name="default_sound"></div><div><label>Channel</label><input name="default_channel"></div></div><div class="row"><div><label>Icon</label><input name="default_icon"></div><div><label>Category</label><input name="default_category"></div></div><button class="button">{{ __('mobile_settings.save_push') }}</button></form>
<h3>{{ __('mobile_settings.configured') }}</h3>@forelse($providers as $p)<div class="log">{{ $p->app }} · {{ $p->platform }} · {{ $p->environment }} · {{ $p->enabled?__('mobile_settings.on'):__('mobile_settings.off') }}</div>@empty<p class="muted">{{ __('mobile_settings.empty') }}</p>@endforelse</section>
<section class="card"><h2>{{ __('mobile_settings.test_title') }}</h2><form method="post" action="{{ route('admin.mobile-settings.test') }}">@csrf<label>{{ __('mobile_settings.device') }}</label><select name="device_id">@foreach($devices as $d)<option value="{{ $d->id }}">#{{ $d->id }} · {{ $d->app }} · {{ $d->platform }} · {{ $d->environment }}</option>@endforeach</select>
<div class="row"><div><label>{{ __('mobile_settings.title_ar') }}</label><input name="title_ar" required></div><div><label>{{ __('mobile_settings.title_en') }}</label><input name="title_en" required></div></div><div class="row"><div><label>{{ __('mobile_settings.body_ar') }}</label><textarea name="body_ar" required></textarea></div><div><label>{{ __('mobile_settings.body_en') }}</label><textarea name="body_en" required></textarea></div></div><button class="button">{{ __('mobile_settings.send_test') }}</button></form>
<h3>{{ __('mobile_settings.delivery_log') }}</h3>@forelse($logs as $log)<div class="log">#{{ $log->id }} · {{ $log->app }}/{{ $log->platform }}/{{ $log->environment }} · <strong>{{ $log->status }}</strong>@if($log->error_code) · {{ $log->error_code }}@endif</div>@empty<p class="muted">{{ __('mobile_settings.empty') }}</p>@endforelse</section></div></main></div></body></html>
