<!doctype html>
<html lang="{{ str_replace('_','-',app()->getLocale()) }}" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ app()->getLocale()==='ar'?'إدارة متاجر التجزئة':'Retail Store Provisioning' }} · FOODEX</title>
<style>
body{margin:0;background:#f5f7fa;color:#17202a}.page{max-width:1500px;margin:auto;padding:28px}.head,.row,.actions{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.panel,.card{background:#fff;border:1px solid #e2e8f0;border-radius:16px}.panel{padding:20px;margin:18px 0}.card{padding:16px;margin:12px 0}.muted{color:#64748b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px}input,select,button{font:inherit;border:1px solid #cbd5e1;border-radius:10px;padding:9px 11px}.btn{cursor:pointer;font-weight:700}.primary{background:#0f172a;color:#fff}.danger{background:#fff1f2;color:#9f1239}.success{background:#ecfdf5;color:#065f46}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#e2e8f0}.active{background:#dcfce7;color:#166534}.inactive{background:#fee2e2;color:#991b1b}.notice,.errors{padding:12px;border-radius:12px}.notice{background:#f0fdf4}.errors{background:#fff1f2}.assignment{padding:10px;border-top:1px solid #e2e8f0}@media(max-width:720px){.page{padding:14px}}
</style>@include('admin._brand-components')</head>
<body><main class="page foodex-admin-page">
@php($ar=app()->getLocale()==='ar')
<div class="head"><div><div class="muted">FOODEX · SUPER_ADMIN</div><h1>{{ $ar?'إدارة متاجر التجزئة':'Retail Store Provisioning' }}</h1><p class="muted">{{ $ar?'إنشاء متاجر التجزئة وتعيين المدراء والأدوار وإدارة الدخول للدعم بشكل صريح ومدقق.':'Create Retail stores, assign managers and store roles, and enter audited support context explicitly.' }}</p></div><a href="{{ route('admin.index') }}">{{ $ar?'العودة للوحة':'Back to dashboard' }}</a></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<section class="panel"><h2>{{ $ar?'إنشاء متجر جديد':'Provision a new retail store' }}</h2>
<form method="post" action="{{ route('admin.retail-stores.store') }}">@csrf
<div class="grid"><input name="code" required placeholder="STORE_CODE"><input name="name" required placeholder="{{ $ar?'اسم المتجر':'Store name' }}"><select name="manager_mode" id="manager_mode"><option value="existing">{{ $ar?'اختيار مستخدم موجود':'Select existing user' }}</option><option value="new">{{ $ar?'إنشاء مدير جديد':'Create new manager' }}</option></select><select name="manager_user_id"><option value="">{{ $ar?'اختر المستخدم':'Select user' }}</option>@foreach($users as $managedUser)<option value="{{ $managedUser->id }}">{{ $managedUser->name }} · {{ $managedUser->email }}</option>@endforeach</select><input name="manager_name" placeholder="{{ $ar?'اسم المدير الجديد':'New manager name' }}"><input name="manager_email" type="email" placeholder="{{ $ar?'بريد المدير':'Manager email' }}"><input name="manager_password" type="password" placeholder="{{ $ar?'كلمة المرور':'Password' }}"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked> {{ $ar?'نشط':'Active' }}</label></div>
<p class="muted">{{ $ar?'عند اختيار مستخدم موجود تجاهل حقول المدير الجديد.':'When selecting an existing user, new-manager fields are ignored.' }}</p><button class="btn primary">{{ $ar?'إنشاء وتعيين المدير':'Create store & assign manager' }}</button></form></section>

<section class="panel"><div class="head"><h2>{{ $ar?'متاجر التجزئة':'Retail Stores' }}</h2><form method="get"><input name="q" value="{{ $search }}" placeholder="{{ $ar?'بحث بالاسم أو الكود':'Search name or code' }}"><button class="btn">{{ $ar?'بحث':'Search' }}</button></form></div>
@forelse($stores as $store)<article class="card">
<div class="head"><div><h3>{{ $store->name }} <span class="badge">{{ $store->code }}</span></h3><span class="badge {{ $store->is_active?'active':'inactive' }}">{{ $store->is_active?($ar?'نشط':'Active'):($ar?'غير نشط':'Inactive') }}</span></div><form method="post" action="{{ route('admin.retail-stores.inspect',$store) }}">@csrf<button class="btn success" @disabled(!$store->is_active)>{{ $ar?'إدارة / فحص المتجر':'Manage / Inspect Store' }}</button></form></div>
<form method="post" action="{{ route('admin.retail-stores.update',$store) }}">@csrf @method('patch')<div class="grid"><input name="code" value="{{ $store->code }}" required><input name="name" value="{{ $store->name }}" required><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($store->is_active)> {{ $ar?'نشط':'Active' }}</label><button class="btn primary">{{ $ar?'حفظ':'Save' }}</button></div></form>
<h4>{{ $ar?'المدراء والأدوار':'Managers & store roles' }}</h4>
@foreach($store->storeRoleAssignments as $assignment)<div class="assignment row"><span>{{ $assignment->user?->name }} · {{ $assignment->user?->email }} · <strong>{{ $assignment->role?->code }}</strong></span><form method="post" action="{{ route('admin.retail-stores.roles.remove',[$store,$assignment->id]) }}">@csrf @method('delete')<button class="btn danger">{{ $ar?'إزالة':'Remove' }}</button></form></div>@endforeach
<form method="post" action="{{ route('admin.retail-stores.roles.assign',$store) }}">@csrf<div class="grid"><select name="user_id" required>@foreach($users as $managedUser)<option value="{{ $managedUser->id }}">{{ $managedUser->name }} · {{ $managedUser->email }}</option>@endforeach</select><select name="role_id" required>@foreach($storeRoles as $role)<option value="{{ $role->id }}">{{ $role->name }} ({{ $role->code }})</option>@endforeach</select><button class="btn">{{ $ar?'إسناد الدور':'Assign role' }}</button></div></form>
</article>@empty<p class="muted">{{ $ar?'لا توجد متاجر مطابقة.':'No matching retail stores.' }}</p>@endforelse
{{ $stores->links() }}</section>
</main></body></html>
