<?php

return [
    'abilities' => [
        'platform.manage' => 'Manage platform-wide settings and permissions',
        'security.view' => 'View users, roles and the effective permission matrix',
        'roles.manage' => 'Create, edit, clone, activate and delete delegated roles',
        'users.view' => 'View users and their effective access',
        'users.roles.manage' => 'Assign global and store-scoped roles to users',
        'users.status.manage' => 'Activate and deactivate user accounts',
        'translations.manage' => 'Manage Arabic and English UI translations',
        'system.update' => 'Install validated FOODEX system updates',
        'demo_data.manage' => 'Create and remove isolated non-production FOODEX demo data',
        'settings.view' => 'View operational platform settings',
        'settings.manage' => 'Manage operational platform settings',
        'field_ops.manage' => 'Manage field operations control-plane configuration',
        'territories.manage' => 'Manage geography, service territories and address resolution',
        'mobile_settings.manage' => 'Manage Customer and Driver app release settings',
        'assistant.use' => 'Use the read-only FOODEX management Assistant within authorized business scope',
        'app_preview.view' => 'Open the real Customer and Driver application preview runtime',
        'app_preview.impersonate_customer' => 'Preview the application as an authorized customer identity',
        'app_preview.impersonate_driver' => 'Preview the application as an authorized driver identity',
        'app_preview.publish' => 'Publish and roll back scoped Customer App storefront revisions',
        'push_settings.manage' => 'Manage push notification provider settings',
        'push_settings.test' => 'Send controlled push notification tests',
        'sms_settings.manage' => 'Manage central SMS provider settings',
        'sms_settings.test' => 'Send controlled SMS gateway tests',
        'stores.view' => 'View stores and channel configuration',
        'stores.manage' => 'Manage stores and channel configuration',
        'b2b.accounts.view' => 'View B2B customer accounts',
        'b2b.accounts.manage' => 'Manage B2B customer accounts',
        'b2b.pricing.view' => 'View B2B pricing',
        'b2b.pricing.manage' => 'Manage B2B pricing and approvals',
        'catalog.view' => 'View products and catalog data',
        'catalog.create' => 'Create products and catalog data',
        'catalog.edit' => 'Edit products and catalog data',
        'catalog.delete' => 'Delete products and catalog data',
        'catalog.manage' => 'Manage products and catalog data',
        'lookups.view' => 'View business lookup and master data',
        'lookups.manage' => 'Manage business lookup and master data',
        'inventory.view' => 'View inventory',
        'inventory.adjust' => 'Adjust inventory quantities',
        'inventory.manage' => 'Manage inventory',
        'inventory.replenishment_mapping.manage' => 'Map wholesale products into retail inventory units',
        'orders.view' => 'View orders',
        'orders.edit' => 'Edit order details where business rules allow',
        'orders.approve' => 'Approve controlled order transitions',
        'orders.manage' => 'Manage orders',
        'customers.view' => 'View customer records',
        'customers.create' => 'Create customer records where permitted',
        'customers.edit' => 'Edit customer records',
        'customers.delete' => 'Delete or archive customer records where permitted',
        'customers.manage' => 'Manage customer records',
        'promotions.view' => 'View promotions and storefront content',
        'promotions.manage' => 'Manage promotions and storefront content',
        'finance.view' => 'View finance and invoice data',
        'finance.manage' => 'Manage finance and invoices',
        'reports.view' => 'View operational and business reports',
        'reports.export' => 'Export authorized reports',
        'support.view' => 'View customer support operations',
        'support.manage' => 'Manage customer support operations',
        'notifications.view' => 'View notification administration',
        'notifications.manage' => 'Manage notification content and targeting',
        'coupons.view' => 'View coupon administration',
        'coupons.manage' => 'Create, edit, activate and retire coupons',
        'live_ads.view' => 'View live advertising administration',
        'live_ads.manage' => 'Create, edit, schedule and retire live ads',
        'drivers.tracking.view' => 'View live driver locations within authorized store and channel scope',
        'drivers.tracking.history' => 'View retained driver location history within authorized scope',
        'drivers.tracking.manage' => 'Manage driver tracking policy and retention settings',
        'drivers.b2b.view' => 'View B2B drivers and delivery operations',
        'drivers.b2b.manage' => 'Manage B2B drivers and delivery operations',
        'drivers.b2c.view' => 'View Retail drivers and delivery operations',
        'drivers.b2c.manage' => 'Manage Retail drivers and delivery operations',
        'deliveries.b2b.execute' => 'Execute B2B delivery assignments',
        'deliveries.b2c.execute' => 'Execute Retail delivery assignments',
        'van.login' => 'Use the Van application runtime',
        'van.support.view' => 'View sanitized Van runtime support diagnostics',
    ],

    'roles' => [
        'SUPER_ADMIN' => ['*'],
        'B2B_ADMIN' => [
            'stores.view',
            'b2b.accounts.view', 'b2b.accounts.manage', 'b2b.pricing.view', 'b2b.pricing.manage',
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.manage',
            'lookups.view', 'lookups.manage',
            'inventory.view', 'inventory.adjust', 'inventory.manage', 'inventory.replenishment_mapping.manage',
            'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'finance.view', 'finance.manage', 'reports.view', 'reports.export',
            'settings.view', 'settings.manage', 'assistant.use',
            'app_preview.view', 'app_preview.impersonate_customer', 'app_preview.impersonate_driver', 'app_preview.publish',
            'drivers.tracking.view', 'drivers.tracking.history', 'drivers.tracking.manage',
            'drivers.b2b.view', 'drivers.b2b.manage', 'notifications.view', 'notifications.manage',
            'coupons.view', 'coupons.manage', 'live_ads.view', 'live_ads.manage',
        ],
        'B2C_STORE_ADMIN' => [
            'stores.view',
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.delete', 'catalog.manage',
            'lookups.view', 'lookups.manage',
            'inventory.view', 'inventory.adjust', 'inventory.manage',
            'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'customers.view', 'customers.create', 'customers.edit', 'customers.delete', 'customers.manage',
            'promotions.view', 'promotions.manage', 'finance.view', 'finance.manage', 'reports.view', 'reports.export',
            'settings.view', 'settings.manage', 'assistant.use',
            'app_preview.view', 'app_preview.impersonate_customer', 'app_preview.impersonate_driver', 'app_preview.publish',
            'drivers.tracking.view', 'drivers.tracking.history', 'drivers.tracking.manage',
            'drivers.b2c.view', 'drivers.b2c.manage', 'notifications.view', 'notifications.manage',
            'coupons.view', 'coupons.manage', 'live_ads.view', 'live_ads.manage',
        ],
        // Global operational roles are wholesale-only. Retail counterparts are store-only.
        'OPERATIONS' => [
            'stores.view', 'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'assistant.use',
            'drivers.tracking.view', 'drivers.b2b.view', 'drivers.b2b.manage', 'reports.view',
        ],
        'INVENTORY' => [
            'stores.view', 'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.manage', 'lookups.view',
            'assistant.use',
            'inventory.view', 'inventory.adjust', 'inventory.manage',
        ],
        'FINANCE' => ['assistant.use', 'stores.view', 'finance.view', 'finance.manage', 'reports.view', 'reports.export'],
        'CUSTOMER_SUPPORT' => [
            'assistant.use', 'stores.view', 'b2b.accounts.view', 'b2b.accounts.manage',
            'support.view', 'support.manage', 'customers.view', 'customers.edit', 'customers.manage', 'orders.view', 'orders.manage',
        ],
        'RETAIL_OPERATIONS' => [
            'assistant.use', 'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'drivers.tracking.view', 'drivers.b2c.view', 'drivers.b2c.manage', 'reports.view',
        ],
        'RETAIL_INVENTORY' => [
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.manage', 'lookups.view',
            'assistant.use',
            'inventory.view', 'inventory.adjust', 'inventory.manage', 'inventory.replenishment_mapping.manage',
        ],
        'RETAIL_FINANCE' => ['assistant.use', 'finance.view', 'finance.manage', 'reports.view', 'reports.export'],
        'RETAIL_CUSTOMER_SUPPORT' => [
            'assistant.use', 'support.view', 'support.manage', 'customers.view', 'customers.edit', 'customers.manage', 'orders.view', 'orders.manage',
        ],
        'B2B_DRIVER' => ['deliveries.b2b.execute'],
        'B2C_DRIVER' => ['deliveries.b2c.execute'],
    ],
];
