<?php

return [
    'abilities' => [
        'platform.manage' => 'Manage platform-wide settings and permissions',
        'security.view' => 'View users, roles and the effective permission matrix',
        'roles.manage' => 'Create, edit, clone, activate and delete delegated roles',
        'users.view' => 'View users and their effective access',
        'users.roles.manage' => 'Assign global and store-scoped roles to users',
        'users.status.manage' => 'Activate and deactivate user accounts',
        'translations.manage' => 'Manage Arabic and English UI translations',
        'system.update' => 'Install validated FOODEX system updates',
        'demo_data.manage' => 'Create and remove isolated non-production FOODEX demo data',
        'settings.view' => 'View operational platform settings',
        'settings.manage' => 'Manage operational platform settings',
        'mobile_settings.manage' => 'Manage Customer and Driver app release settings',
        'push_settings.manage' => 'Manage push notification provider settings',
        'push_settings.test' => 'Send controlled push notification tests',
        'stores.view' => 'View stores and channel configuration',
        'stores.manage' => 'Manage stores and channel configuration',
        'b2b.accounts.view' => 'View B2B customer accounts',
        'b2b.accounts.manage' => 'Manage B2B customer accounts',
        'b2b.pricing.view' => 'View B2B pricing',
        'b2b.pricing.manage' => 'Manage B2B pricing and approvals',
        'catalog.view' => 'View products and catalog data',
        'catalog.create' => 'Create products and catalog data',
        'catalog.edit' => 'Edit products and catalog data',
        'catalog.delete' => 'Delete products and catalog data',
        'catalog.manage' => 'Manage products and catalog data',
        'inventory.view' => 'View inventory',
        'inventory.adjust' => 'Adjust inventory quantities',
        'inventory.manage' => 'Manage inventory',
        'orders.view' => 'View orders',
        'orders.edit' => 'Edit order details where business rules allow',
        'orders.approve' => 'Approve controlled order transitions',
        'orders.manage' => 'Manage orders',
        'customers.view' => 'View customer records',
        'customers.create' => 'Create customer records where permitted',
        'customers.edit' => 'Edit customer records',
        'customers.delete' => 'Delete or archive customer records where permitted',
        'customers.manage' => 'Manage customer records',
        'promotions.view' => 'View promotions and storefront content',
        'promotions.manage' => 'Manage promotions and storefront content',
        'finance.view' => 'View finance and invoice data',
        'finance.manage' => 'Manage finance and invoices',
        'reports.view' => 'View operational and business reports',
        'reports.export' => 'Export authorized reports',
        'support.view' => 'View customer support operations',
        'support.manage' => 'Manage customer support operations',
        'notifications.view' => 'View notification administration',
        'notifications.manage' => 'Manage notification content and targeting',
        'drivers.b2b.view' => 'View B2B drivers and delivery operations',
        'drivers.b2b.manage' => 'Manage B2B drivers and delivery operations',
        'drivers.b2c.view' => 'View B2C drivers and delivery operations',
        'drivers.b2c.manage' => 'Manage B2C drivers and delivery operations',
        'deliveries.b2b.execute' => 'Execute B2B delivery assignments',
        'deliveries.b2c.execute' => 'Execute B2C delivery assignments',
    ],

    'roles' => [
        'SUPER_ADMIN' => ['*'],
        'B2B_ADMIN' => [
            'stores.view',
            'b2b.accounts.view', 'b2b.accounts.manage', 'b2b.pricing.view', 'b2b.pricing.manage',
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.manage',
            'inventory.view', 'inventory.adjust', 'inventory.manage',
            'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'finance.view', 'finance.manage', 'reports.view', 'reports.export',
            'drivers.b2b.view', 'drivers.b2b.manage',
        ],
        'B2C_STORE_ADMIN' => [
            'stores.view',
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.delete', 'catalog.manage',
            'inventory.view', 'inventory.adjust', 'inventory.manage',
            'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'customers.view', 'customers.create', 'customers.edit', 'customers.manage',
            'promotions.view', 'promotions.manage', 'reports.view', 'reports.export',
            'drivers.b2c.view', 'drivers.b2c.manage',
        ],
        'OPERATIONS' => [
            'orders.view', 'orders.edit', 'orders.approve', 'orders.manage',
            'drivers.b2b.view', 'drivers.b2b.manage', 'drivers.b2c.view', 'drivers.b2c.manage', 'reports.view',
        ],
        'INVENTORY' => [
            'catalog.view', 'catalog.create', 'catalog.edit', 'catalog.manage',
            'inventory.view', 'inventory.adjust', 'inventory.manage',
        ],
        'FINANCE' => ['finance.view', 'finance.manage', 'reports.view', 'reports.export'],
        'CUSTOMER_SUPPORT' => [
            'support.view', 'support.manage', 'customers.view', 'customers.edit', 'customers.manage', 'orders.view', 'orders.manage',
        ],
        'B2B_DRIVER' => ['deliveries.b2b.execute'],
        'B2C_DRIVER' => ['deliveries.b2c.execute'],
    ],
];
