name: foodex_customer_app
description: FOODEX Customer bootstrap foundation.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^8.2.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/splash_full.png
